#if !canImport(ObjectiveC)
import XCTest

extension RouterPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouterPerformanceTests = [
        ("testCaseInsensitivePerformance", testCaseInsensitivePerformance),
        ("testCaseInsensitiveRoutingMatchFirstPerformance", testCaseInsensitiveRoutingMatchFirstPerformance),
        ("testCaseInsensitiveRoutingMatchLastPerformance", testCaseInsensitiveRoutingMatchLastPerformance),
        ("testCaseSensitivePerformance", testCaseSensitivePerformance),
        ("testMinimalEarlyFailPerformance", testMinimalEarlyFailPerformance),
        ("testMinimalRouterCaseInsensitivePerformance", testMinimalRouterCaseInsensitivePerformance),
        ("testMinimalRouterCaseSensitivePerformance", testMinimalRouterCaseSensitivePerformance),
    ]
}

extension RouterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouterTests = [
        ("testAnyRouting", testAnyRouting),
        ("testCaseInsensitiveRouting", testCaseInsensitiveRouting),
        ("testCaseSensitiveRouting", testCaseSensitiveRouting),
        ("testCatchAllNested", testCatchAllNested),
        ("testDocBlock", testDocBlock),
        ("testDocs2", testDocs2),
        ("testDocs", testDocs),
        ("testParameterPercentDecoding", testParameterPercentDecoding),
        ("testRouter", testRouter),
        ("testRouterSuffixes", testRouterSuffixes),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RouterPerformanceTests.__allTests__RouterPerformanceTests),
        testCase(RouterTests.__allTests__RouterTests),
    ]
}
#endif
