#if !canImport(ObjectiveC)
import XCTest

extension RouterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouterTests = [
        ("testAnyRouting", testAnyRouting),
        ("testCaseInsensitiveRouting", testCaseInsensitiveRouting),
        ("testCaseSensitiveRouting", testCaseSensitiveRouting),
        ("testDocBlock", testDocBlock),
        ("testDocs2", testDocs2),
        ("testDocs", testDocs),
        ("testPerformance", testPerformance),
        ("testRouter", testRouter),
        ("testRouterSuffixes", testRouterSuffixes),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RouterTests.__allTests__RouterTests),
    ]
}
#endif
